// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lm
arma::mat lm(arma::vec Y, arma::mat X, Rcpp::List Hypers, Rcpp::List Inits, int NSims);
RcppExport SEXP _lmBayes_lm(SEXP YSEXP, SEXP XSEXP, SEXP HypersSEXP, SEXP InitsSEXP, SEXP NSimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Hypers(HypersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Inits(InitsSEXP);
    Rcpp::traits::input_parameter< int >::type NSims(NSimsSEXP);
    rcpp_result_gen = Rcpp::wrap(lm(Y, X, Hypers, Inits, NSims));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lmBayes_lm", (DL_FUNC) &_lmBayes_lm, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_lmBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
